services:
  postgres:
    image: postgres:16-alpine
    container_name: ferilo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferilo
    ports:
      - '5432:5432'
    volumes:
      - ferilo_pg_data:/var/lib/postgresql/data

volumes:
  ferilo_pg_data:
